sudo: required
language: go
go:
  - 1.10.3
install: true
script:
  - ./deploy.sh
branches:
  only:
  # - deploy
  - master
notifications:
  slack:
    rooms:
    - jweboytm:woLS6D9oasTaWyC1Ks4zqCne
    on_success: change
    on_failure: always
    on_pull_requests: false
