sudo: required
language: go
go:
  - "1.10.3"
before_install: 
  - echo GOPATH=HOME/gopath/src/github.com/jweboy/api-server
  - go get -u github.com/kardianos/govendor
  - govendor init
  - govendor add +external
  - govendor install +local
script:
  - make
    # - export PATH=$PATH:$HOME/gopath/src/github.com/jweboy/api-server/bin/
    # - go get -v github.com/Masterminds/glide
    # - cd src/github.com/Masterminds/glide && go install && cd -
# services:
#   docker
# script:
#   - docker build -t jweboy/apiserver:latest .
#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#   - docker push jweboy/apiserver:latest
branches:
  only:
  - deploy
notifications:
  slack: 
    rooms:
      - jweboytm:woLS6D9oasTaWyC1Ks4zqCne
    on_success: change
    on_failure: always
    on_pull_requests: false