sudo: required
services:
  - docker
language: go
go:
  - 1.11.2
install: true
    
before_install:
- openssl aes-256-cbc -K $encrypted_67f4f4e45ba3_key -iv $encrypted_67f4f4e45ba3_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d

after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh root@118.24.155.105 -o StrictHostKeyChecking=no 'docker pull jweboy/apiserver && exit'

script:
  - "./deploy.sh"

branches:
  only:
  # - deploy
  # - master
  # - improve-code
addons:
  ssh_known_hosts:
  - 118.24.155.105

notifications:
  slack:
    rooms:
    - jweboytm:woLS6D9oasTaWyC1Ks4zqCne
    on_success: always
    on_failure: always
    on_pull_requests: false

